name: Python Checks
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: tests/dev-requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --disable-pip-version-check wheel pip-tools
        pip-sync tests/dev-requirements.txt
        python -m pip install --disable-pip-version-check --no-deps .
    - name: Lint
      run: |
        echo "::add-matcher::.github/pylama_matcher.json"
        pylama --options tox.ini
  autoformat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --disable-pip-version-check black isort
    - name: Autoformatter
      run: |
        black --diff .
        isort --atomic --profile black --check-only .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: tests/dev-requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --disable-pip-version-check -r tests/dev-requirements.txt
        python -m pip install --disable-pip-version-check -e .
    - name: Get current date
      id: date
      run: echo "::set-output name=curmonth::$(date +'%Y-%m')"
    - name: Test with pytest
      timeout-minutes: 10
      run: |
        pytest --durations=50 -v